apiVersion: v1
kind: Service
metadata:
  labels:
    app: counter-app
  name: counter-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: counter-app