apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis-cluster
  name: redis-cluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - image: redis
        name: redis-cluster
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster
  name: redis-cluster
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: redis-cluster
status:
  loadBalancer: {}
